spring.application.name=Day30Class
server.port=8089
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

spring.security.oauth2.client.registration.google.client-id=1039220180815-3vmqdnqfgq8a8morna1mq8uvcs937ue1.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.accessTokenUri=https://wwww.googleapis.com/oauth2/v3/token
# Default settings for serving static resources
spring.security.oauth2.client.registration.github.client-id=Ov23liFoSTurMmGJ6tUf
spring.security.oauth2.client.registration.github.client-secret=6913ab851efea43d3eb12262febd412a4a33efce
spring.web.resources.static-locations=classpath:/static/

