spring.application.name=Day30Class
server.port=8089
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

spring.security.oauth2.client.registration.google.client-id=97750970343-64qp31o9f7akmg7l680val8us2n3bbk3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
#spring.security.oauth2.accessTokenUri=https://wwww.googleapis.com/oauth2/v3/token
# Default settings for serving static resources
spring.web.resources.static-locations=classpath:/static/

