spring.application.name=Day37Logging
server.port=8090
logging.level.root=Info
logging.level.com.graymatter.Day37LoggingApplication=Trace
logging.file.name=logs/app.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss}{blue}%msg%n
logging.console
