spring.application.name=Day33JWT
server.port=8088
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

security.jwt.secret-key=c9c580d0fe695cca7770e97478c585577862e1abd16af6bf8da4cf95aff2d276
security.jwt.expiration-time=3600000